pretrained_base_model_path: "./pretrained_sd_models/stable-diffusion-inpainting"
pretrained_vae_path: "./pretrained_sd_models/sd-vae-ft-mse"
pretrained_referencenet_model_path: "./pretrained_sd_models/stable-diffusion-v1-5"
image_encoder_path: "./pretrained_sd_models/image_encoder"
denoising_unet_path: "weights/tiktokdress/denoising_unet.pth"
reference_unet_path: "weights/tiktokdress/reference_unet.pth"
pose_guider_path: "weights/tiktokdress/pose_guider.pth"
motion_module_path: "weights/tiktokdress/motion_module.pth"


inference_config: "./configs/inference/inference_v2.yaml"
weight_dtype: 'fp16'

width: 384
height: 512
filter_params:
  method: 'butterworth'
  n: 4
  d_s: 0.25
  d_t: 0.25