data:
  train_bs: 1
  train_width: 384
  train_height: 512
  single_video_path: "./examples/videos/00333/00333_resized.mp4"
  single_video_masked_path: "./examples/videos/00333/00333_resized_masked.mp4"
  single_video_mask_path: "./examples/videos/00333/00333_resized_mask.mp4"
  single_video_dwpose_path: "./examples/videos/00333/00333_resized_kps.mp4"
  single_garment_image: "./examples/clothes/00333.png"
  sample_rate: 4 
  n_sample_frames: 24

solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16'
  enable_xformers_memory_efficient_attention: true 
  gradient_checkpointing: false 
  max_train_steps: 200
  max_grad_norm: 1.0
  # lr
  learning_rate: 0.05
  scale_lr: false 
  lr_warmup_steps: 0
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: true 
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

# val:
#   validation_steps: 5000
tracker_name: movingtryon_video_optimize

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

base_model_path: '/root/Projects/pretrained_sd_models/stable-diffusion-inpainting'
reference_model_path: '/root/Projects/pretrained_sd_models/stable-diffusion-v1-5'
vae_model_path: '/root/Projects/pretrained_sd_models/sd-vae-ft-mse'
image_encoder_path: '/root/Projects/pretrained_sd_models/image_encoder'
mm_path: 'exp_output/stage2_from_stage1_1024_ft_upblocks_200k(oot_mask)/motion_module-100000.pth'

weight_dtype: 'fp16'  # [fp16, fp32]
uncond_ratio: 0.1
noise_offset: 0.05
snr_gamma: 0
enable_zero_snr: False 
stage1_ckpt_dir: './exp_output/stage1_1024x768_ft_upblocks'
stage1_ckpt_step: 200000

seed: 10000
resume_from_checkpoint: ''
checkpointing_steps: 50
exp_name: 'stage2_from_stage1_1024_ft_upblocks_200k(oot_mask)_optimization'
output_dir: './exp_output' 