data:
  train_bs: 1
  train_width: 384
  train_height: 512
  meta_paths: "/root/dataset/VVT"
  sample_rate: 4
  n_sample_frames: 12

solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16'
  enable_xformers_memory_efficient_attention: true 
  gradient_checkpointing: false 
  max_train_steps: 100000
  max_grad_norm: 1.0
  # lr
  learning_rate: 1.0e-5
  scale_lr: false 
  lr_warmup_steps: 1
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: true 
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

# val:
#   validation_steps: 5000
tracker_name: movingtryon_video512_ootmask_flow_loss_0.1

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

base_model_path: '/root/Projects/pretrained_sd_models/stable-diffusion-inpainting'
reference_model_path: '/root/Projects/pretrained_sd_models/stable-diffusion-v1-5'
vae_model_path: '/root/Projects/pretrained_sd_models/sd-vae-ft-mse'
image_encoder_path: '/root/Projects/pretrained_sd_models/image_encoder'
mm_path: '/root/Projects/pretrained_sd_models/mm_sd_v15_v2.ckpt'

weight_dtype: 'fp16'  # [fp16, fp32]
uncond_ratio: 0.1
noise_offset: 0.05
snr_gamma: 5.0
enable_zero_snr: True 
stage1_ckpt_dir: './exp_output/stage1_1024x768_ft_upblocks_aug'
stage1_ckpt_step: 200000

seed: 10000
resume_from_checkpoint: 'latest'
checkpointing_steps: 10000
exp_name: 'stage2_vvt512_from_stage1_1024x768_ft_upblocks_aug(oot_mask)_flow_loss_0.1'
output_dir: './exp_output'